# This file was generated by GoReleaser. DO NOT EDIT.
cask "capture" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "944b74f97a273cda8d965c9eff73412fa479ca3b26f83ff00fbbc535ccc75098"
      url "https://github.com/techulus/capture-go/releases/download/v#{version}/capture_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "726d3c70607676396d8ab06ab5cbf4a8f5211e2f19f9f865a2789f3bee8ddfe8"
      url "https://github.com/techulus/capture-go/releases/download/v#{version}/capture_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a8291665bb81a89fd2c9f43feb88f1741502af00247a5208be2fa1c531b63683"
      url "https://github.com/techulus/capture-go/releases/download/v#{version}/capture_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "acfaf398fa4a3cda81ab743cc0b45c10139455685878a13bb9e015836a7d0a94"
      url "https://github.com/techulus/capture-go/releases/download/v#{version}/capture_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capture"
  desc "CLI for taking screenshots, PDFs, and extracting content from web pages"
  homepage "https://capture.page"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capture"

  # No zap stanza required

end
