# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Capture < Formula
  desc "CLI for taking screenshots, PDFs, and extracting content from web pages"
  homepage "https://capture.page"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techulus/capture-go/releases/download/v0.1.0/capture_0.1.0_darwin_amd64.tar.gz"
      sha256 "dcc14c674b59df4877d482cd1d46da72c4c2d22b0fb8bfc3832bda049dd6f018"

      def install
        bin.install "capture"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techulus/capture-go/releases/download/v0.1.0/capture_0.1.0_darwin_arm64.tar.gz"
      sha256 "dfd213079f07158d2e8aa71e9fe016d3068da9e7af7809730c35d56a09358f39"

      def install
        bin.install "capture"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/capture-go/releases/download/v0.1.0/capture_0.1.0_linux_amd64.tar.gz"
      sha256 "da4b4bd56733d54a366956a3061bfcd62345eac8d153fb423fec63ad157b89d4"
      def install
        bin.install "capture"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/capture-go/releases/download/v0.1.0/capture_0.1.0_linux_arm64.tar.gz"
      sha256 "5a18af5bced722e59a3ab060e8ff6bb3d7d44d08a1f3f315e1433b49f62dcbee"
      def install
        bin.install "capture"
      end
    end
  end

  test do
    system "#{bin}/capture", "version"
  end
end
