# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Capture < Formula
  desc "CLI for taking screenshots, PDFs, and extracting content from web pages"
  homepage "https://capture.page"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techulus/capture-go/releases/download/v0.4.0/capture_0.4.0_darwin_amd64.tar.gz"
      sha256 "8ea9c0f07a47f5b4a5bc14f7b6784c1d9cf74c86a3149b2e7cf329cbddf7b14d"

      define_method(:install) do
        bin.install "capture"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techulus/capture-go/releases/download/v0.4.0/capture_0.4.0_darwin_arm64.tar.gz"
      sha256 "e7608413a62cd8598cf28e196d60399f8309ea3aed394abe6890296cadd2eb4a"

      define_method(:install) do
        bin.install "capture"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/capture-go/releases/download/v0.4.0/capture_0.4.0_linux_amd64.tar.gz"
      sha256 "16da9c19c10fd3d443317e328de6c4854929fd3ff031644642f435e46dcfc858"
      define_method(:install) do
        bin.install "capture"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/capture-go/releases/download/v0.4.0/capture_0.4.0_linux_arm64.tar.gz"
      sha256 "a57299770dd2efddbf4471de1cd7a6906594ce87be25d5f0ea880b771d418b0f"
      define_method(:install) do
        bin.install "capture"
      end
    end
  end

  test do
    system "#{bin}/capture", "version"
  end
end
