# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manageprompt < Formula
  desc "Local LLM call debugger"
  homepage "https://github.com/techulus/manage-prompt"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.4.0/manageprompt_0.4.0_darwin_amd64.tar.gz"
      sha256 "8bad39f29f945ff64a77a1a4dff3de448e77c5b80907fd0b811c2d631f06ae15"

      define_method(:install) do
        bin.install "manageprompt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.4.0/manageprompt_0.4.0_darwin_arm64.tar.gz"
      sha256 "1c6494f159bec0e52e1a8861c2de2d85f31d598685a4880a6136db4ba1103cc1"

      define_method(:install) do
        bin.install "manageprompt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.4.0/manageprompt_0.4.0_linux_amd64.tar.gz"
      sha256 "07e4df276e90e89f3d6f91df83a25e0b4601c78e668ee02997e207fbf1a95853"
      define_method(:install) do
        bin.install "manageprompt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.4.0/manageprompt_0.4.0_linux_arm64.tar.gz"
      sha256 "8d4b3a12f1bf68d644219c8a86b2641e46eea08703246f57e10aae40ec26689a"
      define_method(:install) do
        bin.install "manageprompt"
      end
    end
  end

  test do
    system "#{bin}/manageprompt", "version"
  end
end
