# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manageprompt < Formula
  desc "Local LLM call debugger"
  homepage "https://github.com/techulus/manage-prompt"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.1.0/manageprompt_0.1.0_darwin_amd64.tar.gz"
      sha256 "dd4cd70491703339af99622180e675dc793ffa7d95c1d3f94a01f32e0479f1dd"

      def install
        bin.install "manageprompt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.1.0/manageprompt_0.1.0_darwin_arm64.tar.gz"
      sha256 "6c36c5846a79aa2f052d25d8d10a9956c2922ff3e2b0059bf9e6e2a9fe25cbdc"

      def install
        bin.install "manageprompt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.1.0/manageprompt_0.1.0_linux_amd64.tar.gz"
      sha256 "8048f4107b298dacded11fbe711cda9bd8d1e4121c49c8067f8165ff6bc4c9c4"
      def install
        bin.install "manageprompt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.1.0/manageprompt_0.1.0_linux_arm64.tar.gz"
      sha256 "df791d86b9d17fbc4ab901d634956500f68d81de6a8fc52998a5e728d014d941"
      def install
        bin.install "manageprompt"
      end
    end
  end

  test do
    system "#{bin}/manageprompt", "version"
  end
end
