# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manageprompt < Formula
  desc "Local LLM call debugger"
  homepage "https://github.com/techulus/manage-prompt"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.2.0/manageprompt_0.2.0_darwin_amd64.tar.gz"
      sha256 "e36995f1eaa15e2b2bac5d4335073d123f3d8f8d5751c17a948368ff082856b2"

      define_method(:install) do
        bin.install "manageprompt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.2.0/manageprompt_0.2.0_darwin_arm64.tar.gz"
      sha256 "1d614445b6ccd06d1119fe881ac655b23869fe41551fe4285f71024e21d38246"

      define_method(:install) do
        bin.install "manageprompt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.2.0/manageprompt_0.2.0_linux_amd64.tar.gz"
      sha256 "4183c9029118c77cc07ccbbcb7502f74d8c364c6803e1f775fefdb54611c8cb8"
      define_method(:install) do
        bin.install "manageprompt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/manage-prompt/releases/download/v0.2.0/manageprompt_0.2.0_linux_arm64.tar.gz"
      sha256 "85dae342c01506fc297d1119bea758f673da69c67b73e9a5dcee85e86d0bb95b"
      define_method(:install) do
        bin.install "manageprompt"
      end
    end
  end

  test do
    system "#{bin}/manageprompt", "version"
  end
end
