# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Push < Formula
  desc "CLI for sending push notifications via Push by Techulus"
  homepage "https://push.techulus.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techulus/push-cli/releases/download/v0.1.0/push_0.1.0_darwin_amd64.tar.gz"
      sha256 "f559813527c6a7d0818327c1dcec8cd6452782dcfa8c0bc98b1127b6c254864d"

      def install
        bin.install "push"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techulus/push-cli/releases/download/v0.1.0/push_0.1.0_darwin_arm64.tar.gz"
      sha256 "d75e69fdb7626dc1a54823c169813e624cd1a85b2d036c6497686927806f3a85"

      def install
        bin.install "push"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/push-cli/releases/download/v0.1.0/push_0.1.0_linux_amd64.tar.gz"
      sha256 "43befde7d712c435226624e8fe19bd3ec24c3378aba8520304cf0cddd6ceb7ac"
      def install
        bin.install "push"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/push-cli/releases/download/v0.1.0/push_0.1.0_linux_arm64.tar.gz"
      sha256 "37c2cff559287f36f94bc6a9948f13df76f9f58b9e81d720089c2e3f68655ab1"
      def install
        bin.install "push"
      end
    end
  end

  test do
    system "#{bin}/push", "--version"
  end
end
