# typed: false
# frozen_string_literal: true

# This file was generated by the Techulus Cloud release workflow. DO NOT EDIT.
class Tc < Formula
  desc "Techulus Cloud CLI"
  homepage "https://github.com/techulus/cloud"
  version "0.47.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techulus/cloud/releases/download/v0.47.0/tc_0.47.0_darwin_amd64.tar.gz"
      sha256 "beec364b5325cf6e2e3311254886fd3242fa805f61af9b4c8bc3ad6f82819b4e"

      define_method(:install) do
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techulus/cloud/releases/download/v0.47.0/tc_0.47.0_darwin_arm64.tar.gz"
      sha256 "9d1efbffcb365cfd3e640ed2104bf0d0207f89767ceb29848246c4baeadb4849"

      define_method(:install) do
        bin.install "tc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/cloud/releases/download/v0.47.0/tc_0.47.0_linux_amd64.tar.gz"
      sha256 "7822e9533140a8ed01d2f3d12c5e069483ce8a277f8b5eb278a1339f8b825520"

      define_method(:install) do
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/cloud/releases/download/v0.47.0/tc_0.47.0_linux_arm64.tar.gz"
      sha256 "70953417fa7a3e93be0c11b1308711ca515f1d52a748879112bb7e85877bdbd4"

      define_method(:install) do
        bin.install "tc"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tc version")
  end
end
