# typed: false
# frozen_string_literal: true

# This file was generated by the Techulus Cloud release workflow. DO NOT EDIT.
class Tc < Formula
  desc "Techulus Cloud CLI"
  homepage "https://github.com/techulus/cloud"
  version "0.55.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techulus/cloud/releases/download/v0.55.0/tc_0.55.0_darwin_amd64.tar.gz"
      sha256 "a633df5c93f391e21025ac2ce1510447c2e7fc62c131a771f65b8e679d81b0eb"

      define_method(:install) do
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techulus/cloud/releases/download/v0.55.0/tc_0.55.0_darwin_arm64.tar.gz"
      sha256 "3e1a4d4b167be6abf554adfa1237cca28c9f8aee08fab2e5fdb65a128d15adb0"

      define_method(:install) do
        bin.install "tc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/cloud/releases/download/v0.55.0/tc_0.55.0_linux_amd64.tar.gz"
      sha256 "14b3ad572a71eb2c2a4d573555778e7527ece33344078deba11dfe1276541d4b"

      define_method(:install) do
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/cloud/releases/download/v0.55.0/tc_0.55.0_linux_arm64.tar.gz"
      sha256 "f861d8e4b8568dc9791beaf1adb1da4e2b1dc6b4f0150b498b9d6f3dd5c1602e"

      define_method(:install) do
        bin.install "tc"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tc version")
  end
end
