# typed: false
# frozen_string_literal: true

# This file was generated by the Techulus Cloud release workflow. DO NOT EDIT.
class Tc < Formula
  desc "Techulus Cloud CLI"
  homepage "https://github.com/techulus/cloud"
  version "0.53.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techulus/cloud/releases/download/v0.53.0/tc_0.53.0_darwin_amd64.tar.gz"
      sha256 "ab39cda733407f835ca394d50987215ddc19ba7732d1f68b8c8cf4331ed641cb"

      define_method(:install) do
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techulus/cloud/releases/download/v0.53.0/tc_0.53.0_darwin_arm64.tar.gz"
      sha256 "33af5aab090d6d8659c7aa23fc06ef90f4c1322b6b6cf13b87845c982d215ee7"

      define_method(:install) do
        bin.install "tc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/cloud/releases/download/v0.53.0/tc_0.53.0_linux_amd64.tar.gz"
      sha256 "4659d3b17e8d855a0d863c059afdcdf1c2f882502dff7a5d353fa83971847972"

      define_method(:install) do
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techulus/cloud/releases/download/v0.53.0/tc_0.53.0_linux_arm64.tar.gz"
      sha256 "fb0e0655a9c86f2b6f15bad1c6904ae83ce46ff5033700264c2539d9cb155275"

      define_method(:install) do
        bin.install "tc"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tc version")
  end
end
